# _*_ coding: utf-8 _*_

BPA_ORGANIZATION_ID = "bioplatforms-australia"

ORGANIZATIONS = [
    {
        "display_name": "BioPlatforms Australia",
        "name": BPA_ORGANIZATION_ID,
        "image_display_url": "https://data.bioplatforms.com/bpalogo.png",
        "image_url": "https://data.bioplatforms.com/bpalogo.png",
        "title": "BioPlatforms Australia",
        "approval_status": "approved",
        "is_organization": True,
        "state": "active",
        "type": "organization",
    },
    {
        "name": "australian-microbiome",
        "title": "The Australian Microbiome Initiative",
        "display_name": "The Australian Microbiome Initiative",
        "image_url": "https://data.bioplatforms.com/new_ausmicro_logo.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-barcode",
        "title": "Barcode",
        "display_name": "Barcode",
        "image_url": "https://data.bioplatforms.com/barcode.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-great-barrier-reef",
        "title": "Great Barrier Reef",
        "display_name": "Great Barrier Reef",
        "image_url": "https://data.bioplatforms.com/coral.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-melanoma",
        "title": "Melanoma",
        "display_name": "Melanoma",
        "image_url": "https://data.bioplatforms.com/melanoma.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-sepsis",
        "title": "Antibiotic Resistant Sepsis Pathogens",
        "display_name": "Antibiotic Resistant Sepsis Pathogens",
        "image_url": "https://data.bioplatforms.com/sepsis.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-stemcells",
        "title": "Stem Cells",
        "display_name": "Stem Cells",
        "image_url": "https://data.bioplatforms.com/stemcell.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-wheat-cultivars",
        "title": "Wheat Cultivars",
        "display_name": "Wheat Cultivars",
        "image_url": "https://data.bioplatforms.com/wheat.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-wheat-pathogens-genomes",
        "title": "Wheat Pathogens Genomes",
        "display_name": "Wheat Pathogens Genomes",
        "image_url": "https://data.bioplatforms.com/stagonospora_nodorum.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-wheat-pathogens-transcript",
        "title": "Wheat Pathogens Transcript",
        "display_name": "Wheat Pathogens Transcript",
        "image_url": "https://data.bioplatforms.com/wheat.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-omg",
        "title": "Oz Mammals Genomics Initiative",
        "display_name": "Oz Mammals Genomics Initiative",
        "image_url": "https://data.bioplatforms.com/omg-logo.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-plants",
        "title": "Genomics for Australian Plants",
        "display_name": "Genomics for Australian Plants",
        "image_url": "https://data.bioplatforms.com/plants-logo.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "ausarg",
        "title": "Australian Amphibian and Reptile Genomics",
        "display_name": "Australian Amphibian and Reptile Genomics",
        "image_url": "https://data.bioplatforms.com/AusARG-Logo-RGB-150dpi-Transparent.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "threatened-species",
        "title": "Threatened Species Initiative",
        "display_name": "Threatened Species Initiative",
        "image_url": "https://data.bioplatforms.com/Threatened-Species-Initiative-Logo-150dpi-RGB.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "grasslands",
        "title": "Australian Grasslands Initiative",
        "display_name": "Australian Grasslands Initiative",
        "image_url": "https://data.bioplatforms.com/Australian-Grasslands.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
]
