# _*_ coding: utf-8 _*_

BPA_ORGANIZATION_ID = "bioplatforms-australia"

ORGANIZATIONS = [
    {
        "display_name": "Bioplatforms Australia",
        "name": BPA_ORGANIZATION_ID,
        "image_display_url": "https://data.bioplatforms.com/bpalogo.png",
        "image_url": "https://data.bioplatforms.com/bpalogo.png",
        "title": "Bioplatforms Australia",
        "approval_status": "approved",
        "is_organization": True,
        "state": "active",
        "type": "organization",
    },
    {
        "name": "australian-microbiome",
        "title": "The Australian Microbiome Initiative",
        "display_name": "The Australian Microbiome Initiative",
        "image_url": "https://data.bioplatforms.com/new_ausmicro_logo.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-barcode",
        "title": "Barcode",
        "display_name": "Barcode",
        "image_url": "https://data.bioplatforms.com/barcode.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-great-barrier-reef",
        "title": "Great Barrier Reef",
        "display_name": "Great Barrier Reef",
        "image_url": "https://data.bioplatforms.com/coral.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-melanoma",
        "title": "Melanoma",
        "display_name": "Melanoma",
        "image_url": "https://data.bioplatforms.com/melanoma.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-sepsis",
        "title": "Antibiotic Resistant Sepsis Pathogens",
        "display_name": "Antibiotic Resistant Sepsis Pathogens",
        "image_url": "https://data.bioplatforms.com/sepsis.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-stemcells",
        "title": "Stem Cells",
        "display_name": "Stem Cells",
        "image_url": "https://data.bioplatforms.com/stemcell.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-wheat-cultivars",
        "title": "Wheat Cultivars",
        "display_name": "Wheat Cultivars",
        "image_url": "https://data.bioplatforms.com/wheat.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-wheat-pathogens-genomes",
        "title": "Wheat Pathogens Genomes",
        "display_name": "Wheat Pathogens Genomes",
        "image_url": "https://data.bioplatforms.com/stagonospora_nodorum.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-wheat-pathogens-transcript",
        "title": "Wheat Pathogens Transcript",
        "display_name": "Wheat Pathogens Transcript",
        "image_url": "https://data.bioplatforms.com/wheat.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-omg",
        "title": "Oz Mammals Genomics Initiative",
        "display_name": "Oz Mammals Genomics Initiative",
        "image_url": "https://data.bioplatforms.com/omg-logo.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-plants",
        "title": "Genomics for Australian Plants",
        "display_name": "Genomics for Australian Plants",
        "image_url": "https://data.bioplatforms.com/plants-logo.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "ausarg",
        "title": "Australian Amphibian and Reptile Genomics",
        "display_name": "Australian Amphibian and Reptile Genomics",
        "image_url": "https://data.bioplatforms.com/AusARG-Logo-RGB-150dpi-Transparent.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "threatened-species",
        "title": "Threatened Species Initiative",
        "display_name": "Threatened Species Initiative",
        "image_url": "https://data.bioplatforms.com/Threatened-Species-Initiative-Logo-150dpi-RGB.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "grasslands",
        "title": "Australian Grasslands Initiative",
        "display_name": "Australian Grasslands Initiative",
        "image_url": "https://data.bioplatforms.com/Australian-Grasslands.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "plant-pathogen",
        "title": "Plant Pathogen 'Omics",
        "display_name": "Plant Pathogen 'Omics",
        "image_url": "https://data.bioplatforms.com/plant_pathogen.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "pp-consortium-members",
        "title": "Plant Pathogen Project Members",
        "display_name": "Plant Pathogen Project Members",
        "image_url": "https://data.bioplatforms.com/plant_pathogen.png",
        "groups": [{"capacity": "public", "name": 'plant-pathogen'}],
    },
    {
        "name": "fungi",
        "title": "Fungi Functional 'Omics",
        "display_name": "Fungi Functional 'Omics",
        "image_url": "https://data.bioplatforms.com/fungi.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "cipps",
        "title": "ARC for Innovations in Peptide and Protein Science (CIPPS)",
        "display_name": "ARC Centre of Excellence for Innovations in Peptide and Protein Science (CIPPS) ",
        "image_url": "https://data.bioplatforms.com/cipps.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "cipps-consortium-members",
        "title": "CIPPS Project Members",
        "display_name": "ARC for Innovations in Peptide and Protein Science (CIPPS)  Project Members",
        "image_url": "https://data.bioplatforms.com/cipps.png",
        "groups": [{"capacity": "public", "name": 'cipps'}],
    },
    {
        "name": "grassland-consortium-members",
        "title": "Grasslands Project Members",
        "display_name": "Australian Grasslands  Project Members",
        "image_url": "https://data.bioplatforms.com/Australian-Grasslands.png",
        "groups": [{"capacity": "public", "name": 'grasslands'}],
    },
    {
        "name": "grassland-consortium-members",
        "title": "Grasslands Project Members",
        "display_name": "Australian Grasslands  Project Members",
        "image_url": "https://data.bioplatforms.com/Australian-Grasslands.png",
        "groups": [{"capacity": "public", "name": 'grasslands'}],
    },
    {
        "name": "tsi-consortium-members",
        "title": "Threatened Species Project Members",
        "display_name": "Threatened Species Initiative Project Members",
        "image_url": "https://data.bioplatforms.com/Threatened-Species-Initiative-Logo-150dpi-RGB.png",
        "groups": [{"capacity": "public", "name": 'threatened-species'}],
    },
    {
        "name": "ausarg-consortium-members",
        "title": "Australian Amphibian and Reptile Genomics Project Members",
        "display_name": "Australian Amphibian and Reptile Genomics Project Members",
        "image_url": "https://data.bioplatforms.com/AusARG-Logo-RGB-150dpi-Transparent.png",
        "groups": [{"capacity": "public", "name": 'ausarg'}],
    },
    {
        "name": "ppa",
        "title": "Plant Protein Atlas",
        "display_name": "Plant Protein Atlas",
        "image_url": "https://data.bioplatforms.com/ppa.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "ppa-consortium-members",
        "title": "Plant Protein Atlas Project Members",
        "display_name": "Plant Protein Atlas Project Members",
        "image_url": "https://data.bioplatforms.com/ppa.png",
        "groups": [{"capacity": "public", "name": 'ppa'}],
    },
    {
        "name": "aus-fish",
        "title": "Australian Fish Genomics",
        "display_name": "Australian Fish Genomics",
        "image_url": "https://data.bioplatforms.com/fish.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "aus-fish-consortium-members",
        "title": "Australian Fish Genomics Project Members",
        "display_name": "Australian Fish Genomics Project Members",
        "image_url": "https://data.bioplatforms.com/fish.png",
        "groups": [{"capacity": "public", "name": 'aus-fish'}],
    },
    {
        "name": "aus-avian",
        "title": "Australian Avian Genomics",
        "display_name": "Australian Avian Genomics",
        "image_url": "https://data.bioplatforms.com/avian.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "aus-avian-consortium-members",
        "title": "Australian Avian Genomics Project Members",
        "display_name": "Australian Avian Genomics Project Members",
        "image_url": "https://data.bioplatforms.com/avian.png",
        "groups": [{"capacity": "public", "name": 'aus-avian'}],
    },
    {
        "name": "bpa-ipm",
        "title": "Integrated Pest Management 'Omics",
        "display_name": "Integrated Pest Management 'Omics Initiative (IPM 'Omics)",
        "image_url": "https://data.bioplatforms.com/ipm.png",
        "groups": [{"capacity": "public", "name": BPA_ORGANIZATION_ID}],
    },
    {
        "name": "bpa-ipm-consortium-members",
        "title": "IPM 'Omics Project Members",
        "display_name": "IPM 'Omics Project Members",
        "image_url": "https://data.bioplatforms.com/ipm.png",
        "groups": [{"capacity": "public", "name": 'bpa-ipm'}],
    },
    {
        "name": "fungi-consortium-members",
        "title": "Fungi Functional 'Omics Project Members",
        "display_name": "Fungi Functional 'Omics Project Members",
        "image_url": "https://data.bioplatforms.com/fungi.png",
        "groups": [{"capacity": "public", "name": 'fungi'}],
    },
    {
        "name": "platypus-bio-collaboration-members",
        "title": "Platypus Bio Collaboration Members",
        "display_name": "Platypus Bio Collaboration Members",
        "image_url": "https://data.bioplatforms.com/platypus_bio_logo.png",
        "groups": [{"capacity": "public", "name": 'australian-microbiome'}],
    },
]

