from .util import (
    common_values
)

def test_common_values():

    row_objs_missing_first_row_value = [
        {'genus': 'Cryptoblepharus', 'species': 'egeriae', 'library_id': '102.100.100/686210',
         'sample_id': '102.100.100/674082', 'dataset_id': '102.100.100/629232', 'work_order': '',
         'specimen_id': 'BTS107',
         'facility_sample_id': '', 'facility_project_code': 'NA', 'library_type': 'Illumina-DArT',
         'library_prep_date': None, 'library_prepared_by': '', 'experimental_design': '',
         'data_custodian': 'Carolyn Hogg',
         'dna_treatment': '', 'library_index_id': '', 'library_oligo_sequence': '', 'library_pcr_reps': None,
         'library_pcr_cycles': None, 'library_ng_ul': '', 'library_comments': '', 'library_location': '',
         'sequencing_facility': 'Biomolecular Resource Facility', 'n_libraries_pooled': None, 'sequencing_platform': '',
         'flowcell_id': '', 'library_pool_index_id': None, 'library_pool_index_sequence': None,
         'library_pool_oligo_sequence': None, 'voucher_number': None, 'tissue_number': '',
         'voucher_or_tissue_number': None, 'library_layout': '', 'sequencing_model': '', 'library_strategy': '',
         'library_selection': '', 'cell_postion': '', 'data_context': 'Population Genetics',
         'sequencing_kit_chemistry_version': '', 'analysis_software': '', 'analysis_software_version': '',
         'library_construction_protocol': '', 'library_index_seq': '', 'library_index_id_dual': '',
         'library_index_seq_dual': '', 'library_oligo_sequence_dual': '', 'library_source': '', 'fast5_compression': '',
         'model_base_caller': '', 'insert_size_range': '', 'movie_length': '', 'file_type': '', 'flowcell_type': '',
         'bioplatforms_project': 'Threatened Species Initiative', 'bait_set_name': '', 'bait_set_reference': '',
         'ticket': 'BPAOPS-2069',
         'base_url': 'https://downloads-qcif.bioplatforms.com/bpa/tsi_staging/dart/BPAOPS-2069/'},
        {'genus': 'Cryptoblephorus', 'species': 'egeriae', 'library_id': '102.100.100/358977',
      'sample_id': '102.100.100/407224', 'dataset_id': '102.100.100/358806', 'work_order': 14039.0,
      'specimen_id': 'TZ BTS 273', 'facility_sample_id': '', 'facility_project_code': 'NA',
      'library_type': 'Illumina-DArT', 'library_prep_date': None, 'library_prepared_by': '', 'experimental_design': '',
      'data_custodian': 'Carolyn Hogg', 'dna_treatment': '', 'library_index_id': '', 'library_oligo_sequence': '',
      'library_pcr_reps': None, 'library_pcr_cycles': None, 'library_ng_ul': '', 'library_comments': '',
      'library_location': '', 'sequencing_facility': 'Biomolecular Resource Facility', 'n_libraries_pooled': None,
      'sequencing_platform': '', 'flowcell_id': '', 'library_pool_index_id': None, 'library_pool_index_sequence': None,
      'library_pool_oligo_sequence': None, 'voucher_number': None, 'tissue_number': '',
      'voucher_or_tissue_number': None, 'library_layout': '', 'sequencing_model': '', 'library_strategy': '',
      'library_selection': '', 'cell_postion': '', 'data_context': 'Population Genetics',
      'sequencing_kit_chemistry_version': '', 'analysis_software': '', 'analysis_software_version': '',
      'library_construction_protocol': '', 'library_index_seq': '', 'library_index_id_dual': '',
      'library_index_seq_dual': '', 'library_oligo_sequence_dual': '', 'library_source': '', 'fast5_compression': '',
      'model_base_caller': '', 'insert_size_range': '', 'movie_length': '', 'file_type': '', 'flowcell_type': '',
      'bioplatforms_project': 'Threatened Species Initiative', 'bait_set_name': '', 'bait_set_reference': '',
      'ticket': 'BPAOPS-1374', 'base_url': 'https://downloads-qcif.bioplatforms.com/bpa/tsi_staging/dart/BPAOPS-1374/',
      'metadata_revision_date': '2026-01-13',
      'metadata_revision_filename': '20260112_Sample_metadata_COMBINED-FOR-PORTAL_NOLATLON.xlsx',
      'specimen_id_description': 'TZ BTS#', 'institution_name': 'TZ', 'tissue_collection': 'Herpetofauna',
      'tissue_collection_type': 'Zoo', 'sample_custodian': 'Parks Australia', 'sample_type': 'Whole Organism',
      'access_rights': 'No Restrictions', 'tissue_type': 'Toe Clip', 'tissue_preservation': '70 % Ethanol',
      'tissue_preservation_temperature': 'Room Temp', 'sample_quality': 'unknown', 'taxon_id': '250 9230',
      'phylum': 'Chordata', 'class': 'Reptilia', 'order': 'Squamata', 'family': 'Scincidae', 'subspecies': 'NA',
      'scientific_name': 'Cryptoblephorus egeriae', 'scientific_name_note': 'NA',
      'scientific_name_authorship': 'Boulenger, 1888', 'common_name': 'Blue Tailed Skink',
      'collection_date': '2016-01-15', 'collector': 'Taronga Zoo', 'collection_method': '', 'collector_sample_id': '',
      'wild_captive': 'captive', 'source_population': 'Taronga Zoo', 'country': 'Australia',
      'state_or_region': 'New South Wales', 'location_text': "Taronga Zoo, Bradley's Head Rd, Mosman",
      'habitat': 'group 6', 'latitude': -33.9, 'decimal_latitude_public': -33.9, 'longitude': 151.29999999999998,
      'decimal_longitude_public': 151.29999999999998, 'coord_uncertainty_metres': None,
      'genotypic_sex': 'not determined', 'phenotypic_sex': '', 'method_of_determination': 'not determined',
      'certainty': 'not determined', 'lifestage': '', 'birth_date': '2011-12-22', 'death_date': '2012-01-19',
      'health_state': '', 'associated_media': '', 'ancillary_notes': 'TZ historical samples', 'barcode_id': '',
      'ala_specimen_url': '', 'prior_genetics': 'N', 'taxonomic_group': 'Reptile', 'type_status': '',
      'material_extraction_type': 'DNA', 'material_extraction_date': '2022-07-13', 'material_extracted_by': 'USYD_AWGG',
      'material_extraction_method': 'Salting out', 'material_conc_ng_ul': 64.8},
     {'genus': 'Cryptoblephorus', 'species': 'egeriae', 'library_id': '102.100.100/358978',
      'sample_id': '102.100.100/407225', 'dataset_id': '102.100.100/358806', 'work_order': 14039.0,
      'specimen_id': 'TZ BTS 213', 'facility_sample_id': '', 'facility_project_code': 'NA',
      'library_type': 'Illumina-DArT', 'library_prep_date': None, 'library_prepared_by': '', 'experimental_design': '',
      'data_custodian': 'Carolyn Hogg', 'dna_treatment': '', 'library_index_id': '', 'library_oligo_sequence': '',
      'library_pcr_reps': None, 'library_pcr_cycles': None, 'library_ng_ul': '', 'library_comments': '',
      'library_location': '', 'sequencing_facility': 'Biomolecular Resource Facility', 'n_libraries_pooled': None,
      'sequencing_platform': '', 'flowcell_id': '', 'library_pool_index_id': None, 'library_pool_index_sequence': None,
      'library_pool_oligo_sequence': None, 'voucher_number': None, 'tissue_number': '',
      'voucher_or_tissue_number': None, 'library_layout': '', 'sequencing_model': '', 'library_strategy': '',
      'library_selection': '', 'cell_postion': '', 'data_context': 'Population Genetics',
      'sequencing_kit_chemistry_version': '', 'analysis_software': '', 'analysis_software_version': '',
      'library_construction_protocol': '', 'library_index_seq': '', 'library_index_id_dual': '',
      'library_index_seq_dual': '', 'library_oligo_sequence_dual': '', 'library_source': '', 'fast5_compression': '',
      'model_base_caller': '', 'insert_size_range': '', 'movie_length': '', 'file_type': '', 'flowcell_type': '',
      'bioplatforms_project': 'Threatened Species Initiative', 'bait_set_name': '', 'bait_set_reference': '',
      'ticket': 'BPAOPS-1374', 'base_url': 'https://downloads-qcif.bioplatforms.com/bpa/tsi_staging/dart/BPAOPS-1374/',
      'metadata_revision_date': '2026-01-13',
      'metadata_revision_filename': '20260112_Sample_metadata_COMBINED-FOR-PORTAL_NOLATLON.xlsx',
      'specimen_id_description': 'TZ BTS#', 'institution_name': 'TZ', 'tissue_collection': 'Herpetofauna',
      'tissue_collection_type': 'Zoo', 'sample_custodian': 'Parks Australia', 'sample_type': 'Whole Organism',
      'access_rights': 'No Restrictions', 'tissue_type': 'toe Clip', 'tissue_preservation': '70 % Ethanol',
      'tissue_preservation_temperature': 'Room Temp', 'sample_quality': 'unknown', 'taxon_id': '250 9230',
      'phylum': 'Chordata', 'class': 'Reptilia', 'order': 'Squamata', 'family': 'Scincidae', 'subspecies': 'NA',
      'scientific_name': 'Cryptoblephorus egeriae', 'scientific_name_note': 'NA',
      'scientific_name_authorship': 'Boulenger, 1888', 'common_name': 'Blue Tailed Skink',
      'collection_date': '2011-05-12', 'collector': 'Taronga Zoo', 'collection_method': '', 'collector_sample_id': '',
      'wild_captive': 'captive', 'source_population': 'Taronga Zoo', 'country': 'Australia',
      'state_or_region': 'New South Wales', 'location_text': "Taronga Zoo, Bradley's Head Rd, Mosman",
      'habitat': 'TZ BTS3', 'latitude': -33.9, 'decimal_latitude_public': -33.9, 'longitude': 151.29999999999998,
      'decimal_longitude_public': 151.29999999999998, 'coord_uncertainty_metres': None,
      'genotypic_sex': 'not determined', 'phenotypic_sex': '', 'method_of_determination': 'not determined',
      'certainty': 'not determined', 'lifestage': '', 'birth_date': None, 'death_date': None, 'health_state': '',
      'associated_media': '', 'ancillary_notes': 'TZ historical samples', 'barcode_id': '', 'ala_specimen_url': '',
      'prior_genetics': 'N', 'taxonomic_group': 'Reptile', 'type_status': '', 'material_extraction_type': 'DNA',
      'material_extraction_date': '2022-07-13', 'material_extracted_by': 'USYD_AWGG',
      'material_extraction_method': 'Salting out', 'material_conc_ng_ul': 37.9}]

    row_objs_not_blank_first = [{'genus': 'Cryptoblephorus', 'species': 'egeriae', 'library_id': '102.100.100/358977',
      'sample_id': '102.100.100/407224', 'dataset_id': '102.100.100/358806', 'work_order': 14039.0,
      'specimen_id': 'TZ BTS 273', 'facility_sample_id': '', 'facility_project_code': 'NA',
      'library_type': 'Illumina-DArT', 'library_prep_date': None, 'library_prepared_by': '', 'experimental_design': '',
      'data_custodian': 'Carolyn Hogg', 'dna_treatment': '', 'library_index_id': '', 'library_oligo_sequence': '',
      'library_pcr_reps': None, 'library_pcr_cycles': None, 'library_ng_ul': '', 'library_comments': '',
      'library_location': '', 'sequencing_facility': 'Biomolecular Resource Facility', 'n_libraries_pooled': None,
      'sequencing_platform': '', 'flowcell_id': '', 'library_pool_index_id': None, 'library_pool_index_sequence': None,
      'library_pool_oligo_sequence': None, 'voucher_number': None, 'tissue_number': '',
      'voucher_or_tissue_number': None, 'library_layout': '', 'sequencing_model': '', 'library_strategy': '',
      'library_selection': '', 'cell_postion': '', 'data_context': 'Population Genetics',
      'sequencing_kit_chemistry_version': '', 'analysis_software': '', 'analysis_software_version': '',
      'library_construction_protocol': '', 'library_index_seq': '', 'library_index_id_dual': '',
      'library_index_seq_dual': '', 'library_oligo_sequence_dual': '', 'library_source': '', 'fast5_compression': '',
      'model_base_caller': '', 'insert_size_range': '', 'movie_length': '', 'file_type': '', 'flowcell_type': '',
      'bioplatforms_project': 'Threatened Species Initiative', 'bait_set_name': '', 'bait_set_reference': '',
      'ticket': 'BPAOPS-1374', 'base_url': 'https://downloads-qcif.bioplatforms.com/bpa/tsi_staging/dart/BPAOPS-1374/',
      'metadata_revision_date': '2026-01-13',
      'metadata_revision_filename': '20260112_Sample_metadata_COMBINED-FOR-PORTAL_NOLATLON.xlsx',
      'specimen_id_description': 'TZ BTS#', 'institution_name': 'TZ', 'tissue_collection': 'Herpetofauna',
      'tissue_collection_type': 'Zoo', 'sample_custodian': 'Parks Australia', 'sample_type': 'Whole Organism',
      'access_rights': 'No Restrictions', 'tissue_type': 'Toe Clip', 'tissue_preservation': '70 % Ethanol',
      'tissue_preservation_temperature': 'Room Temp', 'sample_quality': 'unknown', 'taxon_id': '250 9230',
      'phylum': 'Chordata', 'class': 'Reptilia', 'order': 'Squamata', 'family': 'Scincidae', 'subspecies': 'NA',
      'scientific_name': 'Cryptoblephorus egeriae', 'scientific_name_note': 'NA',
      'scientific_name_authorship': 'Boulenger, 1888', 'common_name': 'Blue Tailed Skink',
      'collection_date': '2016-01-15', 'collector': 'Taronga Zoo', 'collection_method': '', 'collector_sample_id': '',
      'wild_captive': 'captive', 'source_population': 'Taronga Zoo', 'country': 'Australia',
      'state_or_region': 'New South Wales', 'location_text': "Taronga Zoo, Bradley's Head Rd, Mosman",
      'habitat': 'group 6', 'latitude': -33.9, 'decimal_latitude_public': -33.9, 'longitude': 151.29999999999998,
      'decimal_longitude_public': 151.29999999999998, 'coord_uncertainty_metres': None,
      'genotypic_sex': 'not determined', 'phenotypic_sex': '', 'method_of_determination': 'not determined',
      'certainty': 'not determined', 'lifestage': '', 'birth_date': '2011-12-22', 'death_date': '2012-01-19',
      'health_state': '', 'associated_media': '', 'ancillary_notes': 'TZ historical samples', 'barcode_id': '',
      'ala_specimen_url': '', 'prior_genetics': 'N', 'taxonomic_group': 'Reptile', 'type_status': '',
      'material_extraction_type': 'DNA', 'material_extraction_date': '2022-07-13', 'material_extracted_by': 'USYD_AWGG',
      'material_extraction_method': 'Salting out', 'material_conc_ng_ul': 64.8},
      {'genus': 'Cryptoblephorus', 'species': 'egeriae', 'library_id': '102.100.100/358978',
      'sample_id': '102.100.100/407225', 'dataset_id': '102.100.100/358806', 'work_order': 14039.0,
      'specimen_id': 'TZ BTS 213', 'facility_sample_id': '', 'facility_project_code': 'NA',
      'library_type': 'Illumina-DArT', 'library_prep_date': None, 'library_prepared_by': '', 'experimental_design': '',
      'data_custodian': 'Carolyn Hogg', 'dna_treatment': '', 'library_index_id': '', 'library_oligo_sequence': '',
      'library_pcr_reps': None, 'library_pcr_cycles': None, 'library_ng_ul': '', 'library_comments': '',
      'library_location': '', 'sequencing_facility': 'Biomolecular Resource Facility', 'n_libraries_pooled': None,
      'sequencing_platform': '', 'flowcell_id': '', 'library_pool_index_id': None, 'library_pool_index_sequence': None,
      'library_pool_oligo_sequence': None, 'voucher_number': None, 'tissue_number': '',
      'voucher_or_tissue_number': None, 'library_layout': '', 'sequencing_model': '', 'library_strategy': '',
      'library_selection': '', 'cell_postion': '', 'data_context': 'Population Genetics',
      'sequencing_kit_chemistry_version': '', 'analysis_software': '', 'analysis_software_version': '',
      'library_construction_protocol': '', 'library_index_seq': '', 'library_index_id_dual': '',
      'library_index_seq_dual': '', 'library_oligo_sequence_dual': '', 'library_source': '', 'fast5_compression': '',
      'model_base_caller': '', 'insert_size_range': '', 'movie_length': '', 'file_type': '', 'flowcell_type': '',
      'bioplatforms_project': 'Threatened Species Initiative', 'bait_set_name': '', 'bait_set_reference': '',
      'ticket': 'BPAOPS-1374', 'base_url': 'https://downloads-qcif.bioplatforms.com/bpa/tsi_staging/dart/BPAOPS-1374/',
      'metadata_revision_date': '2026-01-13',
      'metadata_revision_filename': '20260112_Sample_metadata_COMBINED-FOR-PORTAL_NOLATLON.xlsx',
      'specimen_id_description': 'TZ BTS#', 'institution_name': 'TZ', 'tissue_collection': 'Herpetofauna',
      'tissue_collection_type': 'Zoo', 'sample_custodian': 'Parks Australia', 'sample_type': 'Whole Organism',
      'access_rights': 'No Restrictions', 'tissue_type': 'toe Clip', 'tissue_preservation': '70 % Ethanol',
      'tissue_preservation_temperature': 'Room Temp', 'sample_quality': 'unknown', 'taxon_id': '250 9230',
      'phylum': 'Chordata', 'class': 'Reptilia', 'order': 'Squamata', 'family': 'Scincidae', 'subspecies': 'NA',
      'scientific_name': 'Cryptoblephorus egeriae', 'scientific_name_note': 'NA',
      'scientific_name_authorship': 'Boulenger, 1888', 'common_name': 'Blue Tailed Skink',
      'collection_date': '2011-05-12', 'collector': 'Taronga Zoo', 'collection_method': '', 'collector_sample_id': '',
      'wild_captive': 'captive', 'source_population': 'Taronga Zoo', 'country': 'Australia',
      'state_or_region': 'New South Wales', 'location_text': "Taronga Zoo, Bradley's Head Rd, Mosman",
      'habitat': 'TZ BTS3', 'latitude': -33.9, 'decimal_latitude_public': -33.9, 'longitude': 151.29999999999998,
      'decimal_longitude_public': 151.29999999999998, 'coord_uncertainty_metres': None,
      'genotypic_sex': 'not determined', 'phenotypic_sex': '', 'method_of_determination': 'not determined',
      'certainty': 'not determined', 'lifestage': '', 'birth_date': None, 'death_date': None, 'health_state': '',
      'associated_media': '', 'ancillary_notes': 'TZ historical samples', 'barcode_id': '', 'ala_specimen_url': '',
      'prior_genetics': 'N', 'taxonomic_group': 'Reptile', 'type_status': '', 'material_extraction_type': 'DNA',
      'material_extraction_date': '2022-07-13', 'material_extracted_by': 'USYD_AWGG',
      'material_extraction_method': 'Salting out', 'material_conc_ng_ul': 37.9},
         {'genus': 'Cryptoblepharus', 'species': 'egeriae', 'library_id': '102.100.100/686210',
         'sample_id': '102.100.100/674082', 'dataset_id': '102.100.100/629232', 'work_order': '',
         'specimen_id': 'BTS107',
         'facility_sample_id': '', 'facility_project_code': 'NA', 'library_type': 'Illumina-DArT',
         'library_prep_date': None, 'library_prepared_by': '', 'experimental_design': '',
         'data_custodian': 'Carolyn Hogg',
         'dna_treatment': '', 'library_index_id': '', 'library_oligo_sequence': '', 'library_pcr_reps': None,
         'library_pcr_cycles': None, 'library_ng_ul': '', 'library_comments': '', 'library_location': '',
         'sequencing_facility': 'Biomolecular Resource Facility', 'n_libraries_pooled': None, 'sequencing_platform': '',
         'flowcell_id': '', 'library_pool_index_id': None, 'library_pool_index_sequence': None,
         'library_pool_oligo_sequence': None, 'voucher_number': None, 'tissue_number': '',
         'voucher_or_tissue_number': None, 'library_layout': '', 'sequencing_model': '', 'library_strategy': '',
         'library_selection': '', 'cell_postion': '', 'data_context': 'Population Genetics',
         'sequencing_kit_chemistry_version': '', 'analysis_software': '', 'analysis_software_version': '',
         'library_construction_protocol': '', 'library_index_seq': '', 'library_index_id_dual': '',
         'library_index_seq_dual': '', 'library_oligo_sequence_dual': '', 'library_source': '', 'fast5_compression': '',
         'model_base_caller': '', 'insert_size_range': '', 'movie_length': '', 'file_type': '', 'flowcell_type': '',
         'bioplatforms_project': 'Threatened Species Initiative', 'bait_set_name': '', 'bait_set_reference': '',
         'ticket': 'BPAOPS-2069',
         'base_url': 'https://downloads-qcif.bioplatforms.com/bpa/tsi_staging/dart/BPAOPS-2069/'},

    ]

    dogs = [{"name":"Benny", "breed":"Dog", "owner":"Brigette"},
            {"name":"Beau", "breed":"Dog","owner":"Bill"},
            {"name": "Kevin", "breed": "Dog"},
            {"name": "Abby", "breed": "Dog", "owner": "Steve"}
    ]
    dogs_kevin_first = [
        {"name": "Kevin", "breed": "Dog"},
        {"name":"Benny", "breed":"Dog", "owner":"Brigette"},
        {"name":"Beau", "breed":"Dog","owner":"Bill"},
        {"name": "Abby", "breed": "Dog", "owner": "Steve"}
    ]
    dogs_no_breed_first = [
        {"name": "Kevin", "breed": "Dog"},
        {"name":"Benny",  "owner":"Brigette"},
        {"name":"Beau", "breed":"Dog","owner":"Bill"},
        {"name": "Abby", "breed": "Dog", "owner": "Steve"}
    ]
    cats = [{"name":"Bertha", "breed":"Cat","owner":"Brigette"},
            {"name":"Bob", "breed":"Cat","owner":"Brigette"},
            {"name": "Nicky", "breed": "Cat", "owner": "Brigette", "dob":"July 2010"},
            {"name":"Bjorn", "breed":"Cat","dob":"29/02/2024","owner":"Brigette"}]
    pets = dogs + cats

    assert common_values(cats) == {"breed":"Cat", "owner":"Brigette"}

    assert common_values(cats) == {"owner":"Brigette","breed":"Cat"}


    assert common_values(dogs) == {"breed":"Dog"}
    assert common_values(dogs_kevin_first) == {"breed":"Dog"}
    assert common_values(dogs_no_breed_first) == {}
    assert common_values(pets) == {}

    # This has always worked, with old and new versions of common_values.
    assert common_values(row_objs_not_blank_first) == {'coord_uncertainty_metres': None, 'experimental_design': '', 'facility_project_code': 'NA', 'file_type': '', 'data_custodian': 'Carolyn Hogg', 'library_pcr_reps': None, 'bait_set_reference': '', 'analysis_software_version': '', 'library_comments': '', 'voucher_or_tissue_number': None, 'library_strategy': '', 'sequencing_facility': 'Biomolecular Resource Facility', 'data_context': 'Population Genetics', 'voucher_number': None, 'library_prep_date': None, 'sequencing_platform': '', 'library_layout': '', 'flowcell_id': '', 'library_index_seq': '', 'library_index_id': '', 'sequencing_kit_chemistry_version': '', 'flowcell_type': '', 'library_oligo_sequence_dual': '', 'bait_set_name': '', 'bioplatforms_project': 'Threatened Species Initiative', 'library_oligo_sequence': '', 'library_type': 'Illumina-DArT', 'library_source': '', 'n_libraries_pooled': None, 'analysis_software': '', 'fast5_compression': '', 'library_pool_index_sequence': None, 'model_base_caller': '', 'facility_sample_id': '', 'library_location': '', 'library_prepared_by': '', 'library_pool_oligo_sequence': None, 'library_pool_index_id': None, 'movie_length': '', 'library_index_seq_dual': '', 'species': 'egeriae', 'library_index_id_dual': '', 'library_selection': '', 'cell_postion': '', 'library_construction_protocol': '', 'dna_treatment': '', 'library_pcr_cycles': None, 'tissue_number': '', 'sequencing_model': '', 'insert_size_range': '', 'library_ng_ul': ''}
    # This was failing until fixed version of common_values
    assert common_values(row_objs_missing_first_row_value) == {'coord_uncertainty_metres': None, 'experimental_design': '', 'facility_project_code': 'NA', 'file_type': '', 'data_custodian': 'Carolyn Hogg', 'library_pcr_reps': None, 'bait_set_reference': '', 'analysis_software_version': '', 'library_comments': '', 'voucher_or_tissue_number': None, 'library_strategy': '', 'sequencing_facility': 'Biomolecular Resource Facility', 'data_context': 'Population Genetics', 'voucher_number': None, 'library_prep_date': None, 'sequencing_platform': '', 'library_layout': '', 'flowcell_id': '', 'library_index_seq': '', 'library_index_id': '', 'sequencing_kit_chemistry_version': '', 'flowcell_type': '', 'library_oligo_sequence_dual': '', 'bait_set_name': '', 'bioplatforms_project': 'Threatened Species Initiative', 'library_oligo_sequence': '', 'library_type': 'Illumina-DArT', 'library_source': '', 'n_libraries_pooled': None, 'analysis_software': '', 'fast5_compression': '', 'library_pool_index_sequence': None, 'model_base_caller': '', 'facility_sample_id': '', 'library_location': '', 'library_prepared_by': '', 'library_pool_oligo_sequence': None, 'library_pool_index_id': None, 'movie_length': '', 'library_index_seq_dual': '', 'species': 'egeriae', 'library_index_id_dual': '', 'library_selection': '', 'cell_postion': '', 'library_construction_protocol': '', 'dna_treatment': '', 'library_pcr_cycles': None, 'tissue_number': '', 'sequencing_model': '', 'insert_size_range': '', 'library_ng_ul': ''}

